Azure/bicep-registry-modules

modules/deployment-scripts/import-acr/README.md, modules/deployment-scripts/import-acr/main.bicep, modules/deployment-scripts/import-acr/main.json, modules/deployment-scripts/import-acr/test/main.test.bicep, modules/deployment-scripts/import-acr/version.json
- Re-aligning the parameter surface area with that of #84 (This causes a major version bump as we're removing 3 parameters, and changing an array to a string).
- Adding in a retry loop used in #84 to mitigate errors such as RBAC delays
- Shortened the deployment name used to be just the last segment of the fully qualified image name, to give enough headroom from the length limit.
=> UPDATE Deployment script module - Import ACR Images

modules/deployment-scripts/import-acr/README.md, modules/deployment-scripts/import-acr/main.bicep, modules/deployment-scripts/import-acr/main.json, modules/deployment-scripts/import-acr/metadata.json, modules/deployment-scripts/import-acr/version.json
This adds an output of the images that were imported, including the original and the new URIs.
This will be handy for authors that consume this module to leverage the ACR hosted uri of their image.
It also helps by streamlining the dependsOn that would be needed by consuming modules/resources.
Typical output value is
```json
[{
"originalImageUri": "docker.io/bitnami/external-dns:latest",
"acrHostedImageUri": "crtestrq7mjdnsylkok.azurecr.io/bitnami/external-dns:latest"
}, {
"originalImageUri": "quay.io/jetstack/cert-manager-cainjector:v1.7.2",
"acrHostedImageUri": "crtestrq7mjdnsylkok.azurecr.io/jetstack/cert-manager-cainjector:v1.7.2"
}, {
"originalImageUri": "docker.io/bitnami/redis:latest",
"acrHostedImageUri": "crtestrq7mjdnsylkok.azurecr.io/bitnami/redis:latest"
}]
```
=> Module update - ImportAcr - adding an output

modules/deployment-scripts/import-acr/README.md, modules/deployment-scripts/import-acr/main.bicep, modules/deployment-scripts/import-acr/main.json, modules/deployment-scripts/import-acr/version.json
Refining the outputs from the module, to ease the consumption of it by other modules.
Because of the uri portion to the names, it was getting stuck when being consumed in a quickstart, in the azure quickstart repo CI.
=> Import ACR Images - Better output names

modules/deployment-scripts/build-acr/main.bicep, modules/deployment-scripts/build-acr/main.json
It's not possible to build multiple images concurrently from the same git repository.
This PR fixes the naming of the deployment script resource to facilitate that scenario.
=> Deployment Scripts - Acr build concurrency

modules/deployment-scripts/aks-run-command/main.bicep, modules/deployment-scripts/aks-run-command/main.json
=> fix: Update aks-run-command to use 'subscriptionResourceId' 

modules/lz/sub-vending/README.md
LZ Vending - bumping examples version tag as was set to `1.1.0` but when published it was `1.1.1`.
**No changes to bicep code, just docs**
@shenglol @alex-frankel can we get this one approved and merged ASAP so the examples are correct 👍
=> LZ Vending - bumping examples version tag

CONTRIBUTING.md
fixes #210 
Update the [contribution guide](../CONTRIBUTING.md) link to issue template for Module Proposal.
=> Update the Proposal template link closes #210

.github/workflows/get-modules-metadata.yml, scripts/github-actions/get-modules-metadata.js, scripts/github-actions/get-sub-directory-names.js, scripts/github-actions/refresh-module-table.js
Changes in the PR include:
1. Generate modules metadata that'll be used in completion scenarios
2. I'll have a follow up PR to write the generated data to storage account container
Verified the changes in dogfood via:
https://github.com/bhsubra/bicep-registry-modules/pull/1
=> Generate modules metadata

.github/workflows/publish-module.yml, scripts/github-actions/parse-tag.js
Updated publish command to include optional argument --documentationUri. 
Verified the changes here:
https://github.com/bhsubra/bicep-registry-modules/pull/3
https://github.com/bhsubra/bicep-registry-modules/actions/runs/4118663289/jobs/7111463998
=> Update publish command to include optional argument --documentationUri

modules/deployment-scripts/build-acr/README.md, modules/deployment-scripts/build-acr/azAcrBuild.sh, modules/deployment-scripts/build-acr/main.bicep, modules/deployment-scripts/build-acr/main.json, modules/deployment-scripts/build-acr/test/main.test.bicep, modules/deployment-scripts/build-acr/version.json
Whilst not common, some Dockerfiles are expected to run from the context of the repo root to reference other directories above where the dockerfile is located. For this reason we need to be able to seperately deal with the build working directory and Dockerfile subdirectory. 
Example of this scenario can be found in this [repo](https://github.com/azure-octo/dapr-kafka-csharp), in the producer and consumer directory.
=> ACR Build - support more flexible working directory

modules/deployment-scripts/aks-run-helm/README.md, modules/deployment-scripts/aks-run-helm/main.bicep, modules/deployment-scripts/aks-run-helm/main.json, modules/deployment-scripts/aks-run-helm/test/main.test.bicep, modules/deployment-scripts/aks-run-helm/test/prereq.test.bicep, modules/deployment-scripts/aks-run-helm/version.json
The current helm scripting is not working. That has 2 reasons:
- Multiline (every line is executed in a different container which don't share state)
- the order of the arguments given to helm. An example of that here:
[helm update --install cert-manager jetstack/cert-manager](https://cert-manager.io/docs/installation/helm/#4-install-cert-manager) == helm update --install `helmAppName` `helmApp`
Closes #213, #231
=> Change helm scripting

scripts/github-actions/get-changed-module.js
This PR updates the changed-module detection, and no longer considers a module updated if only the README.md has changed. This prevents all the pipelines from kicking off when we have only made documentation updates.
=> Skip module checks if only README has changed

modules/authorization/resource-scope-role-assignment/README.md, modules/authorization/resource-scope-role-assignment/main.bicep, modules/authorization/resource-scope-role-assignment/main.json, modules/authorization/resource-scope-role-assignment/metadata.json, modules/authorization/resource-scope-role-assignment/modules/authorization/genericRoleAssignment.json, modules/authorization/resource-scope-role-assignment/test/main.test.bicep, modules/authorization/resource-scope-role-assignment/version.json
- Closes #354 
- initial module creation
- main and nested json deployment for role assignments on resource scope
- main.test module standalone test with storage and managed identity
- add readme and examples for managed identity assignment on storage account
- brm validate:
- given unique capability of assigning role assignment on resourceId scope 
- no requirement for location, prefix 
- name param is required to be unique guid
Enable GitHub Worksflows in …
=> feat: add authorization/resource-scope-role-assignment module

.github/dependabot.yml
=> ci: Create dependabot.yml for automatically updating github actions

modules/deployment-scripts/create-kv-certificate/README.md, modules/deployment-scripts/create-kv-certificate/main.bicep, modules/deployment-scripts/create-kv-certificate/main.json, modules/deployment-scripts/create-kv-certificate/version.json
Updating the `deployment-scripts/create-kv-certificate` to add a param that controls the running of the role assignment operation defined in the `rbacKv` resource block. 
This is helpful when using an existing Managed Identity that already has the necessary role assigned to it. Without this param, deploys fail with the "role assignment already exists error".
=> refactor: Make role assignment optional when creating certs 

docs/jekyll/Gemfile.lock
The gemlock change was required to run locally but for some reason causes problems in CI.  Reverting for now.
=> fix: Revert gemfile.lock to fix creating module index html

scripts/azure-pipelines/Find-ChangedModule.ps1
Need to force the result to be an array
=> ci: Fix module path filtering logic 2nd iteration

.github/workflows/on-pull-request-check-labels.yml
We should prevent PRs from merging if they have one of the following labels:
=> ci: Disable PR merging with certain labels

modules/ai/cognitiveservices/main.bicep, modules/ai/cognitiveservices/main.json
The AI module was doing deployments in a loop, but the resource only handles one at a time, so I put batchSize(1) for each.
- [ x] This is a bug fix:
=> fix: Add batchSize to deployments

.github/CODEOWNERS
Updated codeowners with @Azure/avm-core-team-technical team, which is the one having Write access to the repository.
=> fix: Update CODEOWNERS to admin group

.prettierignore
Added `avm/` to .prettierignore as it conflicts with its `main.json` & `readme.md` module files
=> Added `avm/` to .prettierignore

avm/res/operational-insights/workspace/README.md, avm/res/operational-insights/workspace/main.bicep, avm/res/operational-insights/workspace/main.json, avm/res/operational-insights/workspace/saved-search/README.md, avm/res/operational-insights/workspace/saved-search/main.bicep, avm/res/operational-insights/workspace/saved-search/main.json, avm/res/operational-insights/workspace/tests/e2e/max/main.test.bicep
PR contains following fixes of the Log Analytics Workspace module:
- fixed static tests by changing the parameter to nullable
- Updated definition of the Role Assignment UDT to the newest version
- Added test of tags in the saved-search child module. Now one of the test deploys tags, the other not.
| Pipeline |
| - |
| [![avm.res.operational-insights.workspace](https://github.com/krbar/bicep-registry-modules/actions/workflows/avm.res.operational-insights.workspace.yml/badge.svg?branch=users%2Fkrbar%2FlogAnalyticsFixes)](https://github.com/krbar/bicep-registry-modules/actions/workflows/avm.res.operational-insights.workspace.yml) |
=> fix: Operational Insights Workspace module - fixed static tests
