- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/on-pull-request.yml
- CONTRIBUTING.md
This PR introduces GitHub Codespaces (dev container) configuration that meets all of the prerequisites for `brm`.
This is helpful when the local development environment is restricted or has environmental issues.
The Codespaces container is based on Ubuntu and includes...
- dotnet 6 🖥️ 
- az cli ☁️ 
- bicep 💪
- brm 🦾
> Codespace config

- scripts/azure-pipelines/Remove-TestResourceGroup.ps1
- scripts/azure-pipelines/utils/AzureResourceUtils.psm1
Update the resource group cleanup scripts to purge resources that may be soft deleted.
Closes https://github.com/Azure/bicep-registry-modules/issues/72.
> Handle soft delete enabled resource types

- scripts/azure-pipelines/utils/AzureResourceUtils.psm1
> Remove -ResourceGroupName from purging kv cmdlet

- CONTRIBUTING.md
> Add a note for internal contributions only

- scripts/azure-pipelines/New-TestResourceGroup.ps1
- scripts/azure-pipelines/utils/AzureResourceUtils.psm1
> Wait for deletion operations to complete before purging resources

- scripts/azure-pipelines/utils/AzureResourceUtils.psm1
Just learnt that `EnabledSoftDelete` is not deprecated yet, so we still need to handle it.
> Handle the case where EnableSoftDelete is false

- modules/deployment-scripts/aks-run-command/README.md
- modules/deployment-scripts/aks-run-command/main.bicep
- modules/deployment-scripts/aks-run-command/main.json
- modules/deployment-scripts/aks-run-command/metadata.json
- modules/deployment-scripts/aks-run-command/test/main.test.bicep
- modules/deployment-scripts/aks-run-command/test/prereq.test.bicep
- modules/deployment-scripts/aks-run-command/version.json
Adds a new module which leverages the AKS Run Command. The Run Command is particularly useful for interacting with private clusters.
Closes #73 
> Deployment script module - AKS Run Command

- modules/network/virtual-network/README.md
- modules/network/virtual-network/main.bicep
- modules/network/virtual-network/main.json
- modules/network/virtual-network/virtualNetworkPeerings/readme.md
- Fixed incorrect resource name
- Fixed typo
- Removed unused parameter in child readme description
Closes #111.
> Minor module internal fixes. Closes #111

- modules/deployment-scripts/wait/README.md
- modules/deployment-scripts/wait/main.bicep
- modules/deployment-scripts/wait/main.json
- modules/deployment-scripts/wait/metadata.json
- modules/deployment-scripts/wait/test/main.test.bicep
- modules/deployment-scripts/wait/version.json
This new module would create a sleep for a configurable number of seconds to be used in other resources DependsOn in order to delay resource creation. 
Closes #114
> Deployment script module - Wait

- modules/azure-gaming/game-dev-vm/README.md
- modules/azure-gaming/game-dev-vm/main.bicep
- modules/azure-gaming/game-dev-vm/main.json
- modules/azure-gaming/game-dev-vm/metadata.json
- modules/azure-gaming/game-dev-vm/test/main.test.bicep
- modules/azure-gaming/game-dev-vm/version.json
> Adding Azure Game Developer Virtual Machine bicep template

- modules/azure-gaming/game-dev-vmss/README.md
- modules/azure-gaming/game-dev-vmss/main.bicep
- modules/azure-gaming/game-dev-vmss/main.json
- modules/azure-gaming/game-dev-vmss/version.json
Enable Cloud Monitoring Extension in GDVMSS.
> Enable Cloud Monitoring Extension for GDVMSS

- modules/network/virtual-network/.bicep/nested_rbac.bicep
- modules/network/virtual-network/README.md
- modules/network/virtual-network/main.bicep
- modules/network/virtual-network/main.json
- modules/network/virtual-network/metadata.json
- modules/network/virtual-network/test/main.test.bicep
- modules/network/virtual-network/virtualNetworkPeerings/deploy.bicep
Uses a preview version ( 2021-04-01-preview ) while there are more recent versions available.
> Fix Bicep errors in Networking module

- modules/azure-gaming/game-dev-vm/main.bicep
- modules/azure-gaming/game-dev-vm/main.json
> API Update for Game Dev VM

- modules/compute/custom-image-vmss/README.md
- modules/compute/custom-image-vmss/main.bicep
- modules/compute/custom-image-vmss/main.json
- modules/compute/custom-image-vmss/metadata.json
- modules/compute/custom-image-vmss/modules/virtualNetworks.bicep
- modules/compute/custom-image-vmss/test/imageConfig.json
- modules/compute/custom-image-vmss/test/main.test.bicep
- modules/compute/custom-image-vmss/version.json
> Adding Custom Image module for VMSS

- modules/deployment-scripts/create-kv-certificate/README.md
- modules/deployment-scripts/create-kv-certificate/main.bicep
- modules/deployment-scripts/create-kv-certificate/main.json
- modules/deployment-scripts/create-kv-certificate/metadata.json
> fix: Module produces 'Resource Dependencies must not use if()' 

- modules/deployment-scripts/build-acr/README.md
- modules/deployment-scripts/build-acr/azAcrBuild.sh
- modules/deployment-scripts/build-acr/main.bicep
- modules/deployment-scripts/build-acr/main.json
- modules/deployment-scripts/build-acr/metadata.json
- modules/deployment-scripts/build-acr/test/main.test.bicep
- modules/deployment-scripts/build-acr/version.json
> New Module: Deployment Scripts - ACR Build

- modules/deployment-scripts/aks-run-command/README.md
- modules/deployment-scripts/aks-run-command/main.bicep
- modules/deployment-scripts/aks-run-command/main.json
- modules/deployment-scripts/aks-run-command/metadata.json
> Update API Versions for aks-run-command

- .devcontainer/devcontainer.json
> Update Codespace with new paths to BRM

- modules/lz/sub-vending/README.md
- modules/lz/sub-vending/main.bicep
- modules/lz/sub-vending/main.json
- modules/lz/sub-vending/src/self/subResourceWrapper/deploy.bicep
- modules/lz/sub-vending/src/self/subResourceWrapper/readme.md
Source: https://github.com/Azure/bicep-lz-vending/pull/28
Fixing these bugs:
- https://github.com/Azure/bicep-lz-vending/issues/26
- https://github.com/Azure/bicep-lz-vending/issues/27
Patch change only as not adding any new parameters etc. just fixing usage of existing parameters in places in the module, as above.
Evidence can be seen in PR: https://github.com/Azure/bicep-lz-vending/pull/28
> Fix minor bugs in `lz-vending` module

- .github/workflows/on-push-main.yml
- .github/workflows/upload-modules-metadata.yml
Write modules metadata to storage account container. This will be used in completion scenarios.
> Write modules metadata to storage account container

- .github/workflows/upload-modules-metadata.yml
- scripts/github-actions/upload-modules-metadata.js
Fixes upload module metadata workflow
> Fix upload module metadata workflow

- modules/lz/sub-vending/README.md
- modules/lz/sub-vending/main.json
- modules/lz/sub-vending/src/self/subResourceWrapper/deploy.bicep
As per https://github.com/Azure/bicep-lz-vending/pull/38 this is adding the release upstream to the registry for consistency.
> Patch Release Update for lz-vending module

- scripts/github-actions/refresh-module-table.js
Auto PR creation is disabled company wise.
> Disable auto PR creation

- modules/storage/storage-account/README.md
- modules/storage/storage-account/main.bicep
- modules/storage/storage-account/main.json
- modules/storage/storage-account/metadata.json
- modules/storage/storage-account/test/main.test.bicep
- modules/storage/storage-account/version.json
> adding storage module

- modules/network/virtual-network/.bicep/nested_rbac.bicep
- modules/network/virtual-network/main.bicep
- modules/network/virtual-network/main.json
> fixed warning- virtual-network

- .gitattributes
- modules/deployment-scripts/create-kv-certificate/README.md
- modules/deployment-scripts/create-kv-certificate/create-kv-cert.sh
- modules/deployment-scripts/create-kv-certificate/main.bicep
- modules/deployment-scripts/create-kv-certificate/main.json
- modules/deployment-scripts/create-kv-certificate/test/main.test.bicep
- modules/deployment-scripts/create-kv-certificate/version.json
> added support for providing validity for cert.

- .github/workflows/fork-on-push-format-workflow.yml
Update autoformat action with option to manual trigger.
> ci: Enable manual trigger of autoformat action

- modules/storage/storage-account/README.md
> doc: Update Storage Account README.md

- modules/storage/storage-account/README.md
- modules/storage/storage-account/main.bicep
- modules/storage/storage-account/main.json
- modules/storage/storage-account/version.json
> feat: add optional I/O to Storage Account

- modules/network/traffic-manager/README.md
- modules/network/traffic-manager/main.bicep
- modules/network/traffic-manager/main.json
- modules/network/traffic-manager/test/main.test.bicep
- modules/network/traffic-manager/test/prereq.test.bicep
- modules/network/traffic-manager/version.json
> feat: added diagnostic settings support for traffic manager.

- modules/storage/log-analytics-workspace/README.md
- modules/storage/log-analytics-workspace/main.bicep
- modules/storage/log-analytics-workspace/main.json
- modules/storage/log-analytics-workspace/metadata.json
- modules/storage/log-analytics-workspace/test/main.test.bicep
- modules/storage/log-analytics-workspace/version.json
closes : https://github.com/Azure/bicep-registry-modules/issues/318
> feat: initial module changes for LAW

- modules/network/nat-gateway/README.md
- modules/network/nat-gateway/main.bicep
- modules/network/nat-gateway/main.json
- modules/network/nat-gateway/metadata.json
- modules/network/nat-gateway/test/main.test.bicep
- modules/network/nat-gateway/test/prereq.test.bicep
- modules/network/nat-gateway/version.json
Fixes: https://github.com/Azure/bicep-registry-modules/issues/328
> feat: initial module for natGateway

- modules/storage/postgresql-single-server/README.md
- modules/storage/postgresql-single-server/main.bicep
- modules/storage/postgresql-single-server/main.json
- modules/storage/postgresql-single-server/metadata.json
- modules/storage/postgresql-single-server/modules/privateEndpoint.bicep
- modules/storage/postgresql-single-server/modules/rbac.bicep
- modules/storage/postgresql-single-server/test/dependencies.test.bicep
- modules/storage/postgresql-single-server/test/main.test.bicep
- modules/storage/postgresql-single-server/version.json
> feat: Postgresql single server module

- modules/network/traffic-manager/README.md
- modules/network/traffic-manager/main.bicep
- modules/network/traffic-manager/main.json
- modules/network/traffic-manager/test/main.test.bicep
- modules/network/traffic-manager/version.json
> feat: add default DNS Name to Traffic Manager

- modules/compute/function-app/README.md
- modules/compute/function-app/main.bicep
- modules/compute/function-app/main.json
- modules/compute/function-app/test/main.test.bicep
- modules/compute/function-app/test/prereq.test.bicep
- modules/compute/function-app/version.json
Closes: https://github.com/Azure/bicep-registry-modules/issues/356
- Tests improvements
- removed hardcode docker image and now user can pass using `dockerImage` param 
- updated readme with version number instead of local path now pointing to public bicep mcr
To trigger GitHub Actions after auto-generation, [add a …
> feat: few improvements to function-app

- modules/network/traffic-manager/README.md
- modules/network/traffic-manager/main.bicep
- modules/network/traffic-manager/main.json
small correction to description.
> fix: traf corrected prefix description

- modules/identity/user-assigned-identity/README.md
- modules/identity/user-assigned-identity/main.bicep
- modules/identity/user-assigned-identity/main.json
- modules/identity/user-assigned-identity/metadata.json
- modules/identity/user-assigned-identity/test/main.test.bicep
- modules/identity/user-assigned-identity/version.json
Closes:  https://github.com/Azure/bicep-registry-modules/issues/358
> feat: (new) Managed Identity initial module changes

- CONTRIBUTING.md
- modules/storage/storage-account/README.md
- modules/storage/storage-account/main.bicep
- modules/storage/storage-account/main.json
> fix: simplify custom typing in storage module

- modules/deployment-scripts/create-kv-sshkeypair/README.md
- modules/deployment-scripts/create-kv-sshkeypair/main.bicep
- modules/deployment-scripts/create-kv-sshkeypair/main.json
- modules/deployment-scripts/create-kv-sshkeypair/metadata.json
- modules/deployment-scripts/create-kv-sshkeypair/scripts/create-ssh-pair.sh
- modules/deployment-scripts/create-kv-sshkeypair/test/main.test.bicep
- modules/deployment-scripts/create-kv-sshkeypair/test/prereq.test.bicep
- modules/deployment-scripts/create-kv-sshkeypair/version.json
Closes: https://github.com/Azure/bicep-registry-modules/issues/384
> feat: SSH Keypair module via deployment script

- .github/workflows/publish-module-index.yml
- .gitignore
- docs/jekyll/Gemfile.lock
- scripts/github-actions/generate-module-index-data.js
- scripts/github-actions/generate-module-index-md.js
- scripts/github-actions/test/test-generate-module-index.bat
- scripts/github-actions/test/test-generate-module-index.js
- scripts/github-actions/test/test-generate-module-index.sh
Part of https://github.com/Azure/bicep/issues/10810
[sample-output.zip](https://github.com/Azure/bicep-registry-modules/files/11764255/sample-output.zip)
> feat: Add descriptions to moduleIndex.json/index.md

- .github/workflows/publish-module-index.yml
- scripts/github-actions/generate-module-index-data.js
> fix: Fix index publishing

- CONTRIBUTING.md
Update to reflect the fact that `metadata description` is now recommended, plus related guidance.
> docs: Update CONTRIBUTING to reflect metadata usage

- modules/ai/cognitiveservices/README.md
- modules/ai/cognitiveservices/main.bicep
- modules/ai/cognitiveservices/main.json
- modules/ai/cognitiveservices/test/main.test.bicep
Closes https://github.com/Azure/bicep-registry-modules/issues/423
> fix: Cognitive Service model deployment SKU

- .github/workflows/publish-module.yml
Tested with a version of the script that skipped the publish step.
> feat: Validate publish is successful

- modules/ai/bing-resource/README.md
- modules/ai/bing-resource/main.bicep
- modules/ai/bing-resource/main.json
- modules/ai/bing-resource/metadata.json
> chore: Remove obs metadata.json (ai/bing-resource) (auto-generated)

- modules/storage/log-analytics-workspace/README.md
- modules/storage/log-analytics-workspace/main.bicep
- modules/storage/log-analytics-workspace/main.json
- modules/storage/log-analytics-workspace/metadata.json
> chore: Remove metadata.json (storage/log-analytics-workspace) (auto-generated)

- modules/storage/cosmos-db/README.md
- modules/storage/cosmos-db/main.bicep
- modules/storage/cosmos-db/main.json
- modules/storage/cosmos-db/metadata.json
> chore: Remove metadata.json (storage/cosmos-db) (auto-generated)

- modules/security/keyvault/README.md
- modules/security/keyvault/main.bicep
- modules/security/keyvault/main.json
- modules/security/keyvault/metadata.json
> chore: Remove metadata.json (security/keyvault) (auto-generated)

- modules/samples/hello-world/README.md
- modules/samples/hello-world/main.bicep
- modules/samples/hello-world/main.json
- modules/samples/hello-world/metadata.json
> chore: Remove metadata.json (samples/hello-world) (auto-generated)

- modules/samples/array-loop/README.md
- modules/samples/array-loop/main.bicep
- modules/samples/array-loop/main.json
- modules/samples/array-loop/metadata.json
> chore: Remove metadata.json (samples/array-loop) (auto-generated)

- modules/observability/grafana/README.md
- modules/observability/grafana/main.bicep
- modules/observability/grafana/main.json
- modules/observability/grafana/metadata.json
> chore: Remove metadata.json (observability/grafana) (auto-generated)

- modules/network/traffic-manager/README.md
- modules/network/traffic-manager/main.bicep
- modules/network/traffic-manager/main.json
- modules/network/traffic-manager/metadata.json
> chore: Remove metadata.json (network/traffic-manager) (auto-generated)

- modules/network/dns-zone/README.md
- modules/network/dns-zone/main.bicep
- modules/network/dns-zone/main.json
- modules/network/dns-zone/metadata.json
- modules/network/nat-gateway/README.md
- modules/network/nat-gateway/main.bicep
- modules/network/nat-gateway/main.json
- modules/network/nat-gateway/metadata.json
> chore: Remove metadata.json (network/nat-gateway) (auto-generated)

- modules/identity/user-assigned-identity/README.md
- modules/identity/user-assigned-identity/main.bicep
- modules/identity/user-assigned-identity/main.json
- modules/identity/user-assigned-identity/metadata.json
> chore: Remove metadata.json (identity/user-assigned-identity) (auto-generated)

- modules/deployment-scripts/import-acr/README.md
- modules/deployment-scripts/import-acr/main.bicep
- modules/deployment-scripts/import-acr/main.json
- modules/deployment-scripts/import-acr/metadata.json
> chore: Remove metadata.json (deployment-scripts/import-acr) (auto-generated)

- modules/deployment-scripts/create-kv-certificate/README.md
- modules/deployment-scripts/create-kv-certificate/main.bicep
- modules/deployment-scripts/create-kv-certificate/main.json
- modules/deployment-scripts/create-kv-certificate/metadata.json
> chore: Remove metadata.json (deployment-scripts/create-kv-certificate) (auto-generated)

- modules/deployment-scripts/aks-run-helm/README.md
- modules/deployment-scripts/aks-run-helm/main.bicep
- modules/deployment-scripts/aks-run-helm/main.json
- modules/deployment-scripts/aks-run-helm/metadata.json
> chore: Remove metadata.json (deployment-scripts/aks-run-helm) (auto-generated)

- modules/cost/subscription-scheduled-action/README.md
- modules/cost/subscription-scheduled-action/main.bicep
- modules/cost/subscription-scheduled-action/main.json
- modules/cost/subscription-scheduled-action/metadata.json
> chore: Remove metadata.json (cost/subscription-scheduled-action) (auto-generated)

- modules/cost/resourcegroup-scheduled-action/README.md
- modules/cost/resourcegroup-scheduled-action/main.bicep
- modules/cost/resourcegroup-scheduled-action/main.json
- modules/cost/resourcegroup-scheduled-action/metadata.json
> chore: Remove metadata.json (cost/resourcegroup-scheduled-action) (auto-generated)

- modules/compute/event-hub/README.md
- modules/compute/event-hub/main.bicep
- modules/compute/event-hub/main.json
- modules/compute/event-hub/metadata.json
> chore: Remove metadata.json (compute/event-hub) (auto-generated)

- modules/compute/container-registry/README.md
- modules/compute/container-registry/main.bicep
- modules/compute/container-registry/main.json
- modules/compute/container-registry/metadata.json
> chore: Remove metadata.json (compute/container-registry) (auto-generated)

- modules/compute/availability-set/README.md
- modules/compute/availability-set/main.bicep
- modules/compute/availability-set/main.json
- modules/compute/availability-set/metadata.json
> chore: Remove metadata.json (compute/availability-set) (auto-generated)

- modules/azure-gaming/game-dev-vm/README.md
- modules/azure-gaming/game-dev-vm/main.bicep
- modules/azure-gaming/game-dev-vm/main.json
- modules/azure-gaming/game-dev-vm/metadata.json
> chore: Remove metadata.json (azure-gaming/game-dev-vm) (auto-generated)

- modules/authorization/resource-scope-role-assignment/README.md
- modules/authorization/resource-scope-role-assignment/main.bicep
- modules/authorization/resource-scope-role-assignment/main.json
- modules/authorization/resource-scope-role-assignment/metadata.json
> chore: Remove metadata.json (authorization/resource-scope-role-assignment) (auto-generated)

- modules/app/dapr-containerapps-environment/README.md
- modules/app/dapr-containerapps-environment/main.bicep
- modules/app/dapr-containerapps-environment/main.json
- modules/app/dapr-containerapps-environment/metadata.json
> chore: Remove metadata.json (app/dapr-containerapps-environment) (auto-generated)

- modules/network/dns-zone/README.md
- modules/network/dns-zone/main.bicep
- modules/network/dns-zone/main.json
- modules/network/dns-zone/metadata.json
- modules/network/nat-gateway/README.md
- modules/network/nat-gateway/main.bicep
- modules/network/nat-gateway/main.json
- modules/network/nat-gateway/metadata.json
Reverts Azure/bicep-registry-modules#474
> fix: Revert "chore: Remove metadata.json (network/nat-gateway) (auto-generated)"

- modules/network/dns-zone/README.md
- modules/network/dns-zone/main.bicep
- modules/network/dns-zone/main.json
- modules/network/dns-zone/metadata.json
> chore: Remove metadata.json (network/dns-zone) (auto-generated)

- CONTRIBUTING.md
- modules/ai/cognitiveservices/main.bicep
- modules/ai/cognitiveservices/main.json
> fix: Update ai/cog to ref cog module by .name instead of name

- modules/ai/cognitiveservices/main.bicep
- modules/ai/cognitiveservices/main.json
- modules/ai/cognitiveservices/version.json
1. OpenAI deployment names need to match what the application developer provides.  For example, if they name the deployment 'foo', then their code with use 'foo'.  The bicep shouldn't generate a name for the deployment because it won't match what the developer expects.  So, I'm changing that to deployment.name.
2. To minimize the amount of code required for the user, we'll now default the sku to Standard/20.
3. To get the 'openai.azure.com' domain you have to specify a customSubDomainName, so we'll default it to the `name` var.
4. networkAcls needs to be `null`, not `{}` if not provided.
If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please …
> fix: Updates to support OpenAI better

- modules/ai/cognitiveservices/README.md
We incremented the minor version with the  latest change. So, updating the README as well.
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called …
> fix: Update ai README with new version number

- modules/search/search-service/main.bicep
- modules/search/search-service/main.json
ARM has a requirement that identity section must be null if sku is free.
- [ x] This is …
> fix: Azure Search: Conditionally set identity based on sku
